apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: v9sn7v89c-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v9sn7v89c-nodejs 
  name: v9sn7v89c-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: v9sn7v89c-nodejs 
